name: AUR Release

on:
  release:
    types: [released]

jobs:
  aur-release:
    runs-on: ubuntu-latest
    container: archlinux:20200705
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
      - name: Publish Release to AUR
        run: |
          ./deploy-aur.sh
        env:
          PACKAGE_NAME: rancher-k3d-bin
          COMMIT_USERNAME: Drone CI
          COMMIT_EMAIL: jonas@dellinger.dev
          COMMIT_MESSAGE: "[CI] Updated to $NEW_RELEASE"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
