name: Staging CI/CD

on:
  release:
    types: [prereleased]

jobs:
  aur-release:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Pre-Release to AUR
        uses: archlinux:20200705
        run: |
          ./deploy-aur.sh
        env:
          PACKAGE_NAME: rancher-k3d-beta-bin
          COMMIT_USERNAME: Drone CI
          COMMIT_EMAIL: jonas@dellinger.dev
          COMMIT_MESSAGE: "[CI] Updated to $NEW_RELEASE"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
